data_root: "data/raw"
demand_shapefile: "data/raw/full/demandHexGrid.shp"
parking_shapefile: "data/raw/full/CharParkfull.shp"
distance_csv: "data/raw/full/shortestpath.csv"
spot_price_csv: "data/raw/ElPrice.csv"
runs_root: "runs"